#!/usr/bin/env python3
"""Generate PipeWire filter-chain config for iMac A2115 2019 4-speaker DSP.

Signal chain (v2.0 — AID20 FIR):
  Input stereo (L, R)
  -> Pre-gain -20 dB [pgL/pgR]
  -> Woofer L/R:  LPF×2 @800 Hz → AID20 PressureResponse⁻¹ FIR (convolver)
  -> Tweeter L/R: +11.885 dB TweeterGain → AID20 TweeterResponse⁻¹ FIR (convolver)

FIR files generated by gen_ir.py from AID20 data (4096-tap, min-phase, 48 kHz).

TweeterGain = +11.885 dB (AID20 field): tweeter HW amp is 11.885 dB louder on real iMac.
Linux uses equal HW amp for all 4 channels → compensate +11.885 dB in software.

Pre-gain -20 dB: woofer FIR peaks +14 dB → -20+14 = -6 dBFS headroom.
                 tweeter: -20 +11.885 +5.4 (FIR peak in passband) = -2.7 dBFS headroom.
"""

XOVER_HZ        = 800.0
XOVER_Q         = 0.70
PRE_GAIN_DB     = -20.0
TWEETER_GAIN_DB = +11.885
IR_DIR          = "/home/mrhogun/.config/pipewire"

nodes = []
links = []


def conv_node(name, filename):
    nodes.append(
        f'          {{ type = builtin  name = {name}  label = convolver'
        f'  config = {{ filename = "{filename}"  channel = 0 }} }}'
    )


def node(name, label, **ctrl):
    ctrl_str = "  ".join(f'"{k}" = {v}' for k, v in ctrl.items())
    nodes.append(
        f'          {{ type = builtin  name = {name}  label = {label}'
        + (f'  control = {{ {ctrl_str} }}' if ctrl else "")
        + " }"
    )


def link(out_node, in_node):
    links.append(f'          {{ output = "{out_node}:Out"  input = "{in_node}:In" }}')


def chain(node_list):
    for a, b in zip(node_list[:-1], node_list[1:]):
        link(a, b)


# --- Pre-gain (highshelf at 30 Hz covers all audible content) ---
node("pgL", "bq_highshelf", Freq=30.0, Q=0.7, Gain=PRE_GAIN_DB)
node("pgR", "bq_highshelf", Freq=30.0, Q=0.7, Gain=PRE_GAIN_DB)

# --- Woofer Left: LPF×2 @800 Hz → AID20 PressureResponse⁻¹ FIR ---
wL = ["pgL"]
for i in range(2):
    n = f"wL_lp{i+1}"
    node(n, "bq_lowpass", Freq=XOVER_HZ, Q=XOVER_Q)
    wL.append(n)
conv_node("wL_ir", f"{IR_DIR}/woofer_ir_L.wav")
wL.append("wL_ir")
chain(wL)

# --- Woofer Right: same ---
wR = ["pgR"]
for i in range(2):
    n = f"wR_lp{i+1}"
    node(n, "bq_lowpass", Freq=XOVER_HZ, Q=XOVER_Q)
    wR.append(n)
conv_node("wR_ir", f"{IR_DIR}/woofer_ir_R.wav")
wR.append("wR_ir")
chain(wR)

# --- Tweeter Left: TweeterGain → HPF×2 @800 Hz → AID20 TweeterResponse⁻¹ FIR ---
node("tgL", "bq_highshelf", Freq=30.0, Q=0.7, Gain=TWEETER_GAIN_DB)
link("pgL", "tgL")
node("tL_hp1", "bq_highpass", Freq=XOVER_HZ, Q=XOVER_Q)
node("tL_hp2", "bq_highpass", Freq=XOVER_HZ, Q=XOVER_Q)
link("tgL", "tL_hp1")
link("tL_hp1", "tL_hp2")
conv_node("tL_ir", f"{IR_DIR}/tweeter_ir_L.wav")
link("tL_hp2", "tL_ir")

# --- Tweeter Right: same ---
node("tgR", "bq_highshelf", Freq=30.0, Q=0.7, Gain=TWEETER_GAIN_DB)
link("pgR", "tgR")
node("tR_hp1", "bq_highpass", Freq=XOVER_HZ, Q=XOVER_Q)
node("tR_hp2", "bq_highpass", Freq=XOVER_HZ, Q=XOVER_Q)
link("tgR", "tR_hp1")
link("tR_hp1", "tR_hp2")
conv_node("tR_ir", f"{IR_DIR}/tweeter_ir_R.wav")
link("tR_hp2", "tR_ir")

# ---------------------------------------------------------------------------
# Assemble config
# ---------------------------------------------------------------------------

nodes_str = "\n".join(nodes)
links_str = "\n".join(links)

conf = f"""context.modules = [
  {{ name = libpipewire-module-filter-chain
    args = {{
      node.description = "iMac A2115 4-Speaker DSP"
      filter.graph = {{
        nodes = [
{nodes_str}
        ]
        links = [
{links_str}
        ]
        inputs  = [ "pgL:In"  "pgR:In" ]
        outputs = [ "tL_ir:Out"  "tR_ir:Out"  "wL_ir:Out"  "wR_ir:Out" ]
      }}
      capture.props = {{
        node.name        = "imac_dsp_in"
        node.description = "iMac Speakers"
        audio.channels   = 2
        audio.position   = [ FL FR ]
        media.class      = "Audio/Sink"
      }}
      playback.props = {{
        node.name        = "imac_dsp_out"
        node.description = "iMac DSP Output"
        node.target      = "alsa_output.pci-0000_00_1f.3.analog-surround-40"
        audio.channels   = 4
        audio.position   = [ FL FR RL RR ]
      }}
    }}
  }}
]
"""

out = "/home/mrhogun/.config/pipewire/pipewire.conf.d/99-imac-dsp.conf"
with open(out, "w") as f:
    f.write(conf)
print(f"Written {len(nodes)} nodes, {len(links)} links to {out}")
